# Generated by Django 4.0 on 2021-12-13 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_room_body_alter_message_body_alter_room_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='body',
        ),
    ]
